<?php
/**
 * 团队业务奖金
 * Created by PhpStorm.
 * User: sundongdong
 * Date: 2017/12/29
 * Time: 17:20
 */
class GroupPriceDecorator extends Decorator {
    public function calcPrice($user, $begin, $end)
    {
        $money = parent::calcPrice($user, $begin, $end); // TODO: Change the autogenerated stub

        $group = 0;
        foreach (TempDb::$mapMonthSaleMoney as $one) {
            $group += $one;
        }
        $price = $group * 0.01;
        echo $user . "当月团队业务奖金" . $price . "\n";

        return $money + $price;
    }
}