<?php
/**
 * 计算当月业务奖金
 * Created by PhpStorm.
 * User: sundongdong
 * Date: 2017/12/29
 * Time: 17:02
 */
class MonthPriceDecorator extends Decorator {
    public function calcPrice($user, $begin, $end)
    {
        $money = parent::calcPrice($user, $begin, $end); // TODO: Change the autogenerated stub
        $price = TempDb::$mapMonthSaleMoney[$user] * 0.03;

        echo $user . "当月业务奖金" . $price . "\n";
        return $money + $price;
    }
}