<?php
/**
 * 累计奖金
 * Created by PhpStorm.
 * User: sundongdong
 * Date: 2017/12/29
 * Time: 17:16
 */
class SumPriceDecorator extends Decorator {
    public function calcPrice($user, $begin, $end)
    {
        $money = parent::calcPrice($user, $begin, $end); // TODO: Change the autogenerated stub

        $sum = 1000000;
        $price = $sum * 0.001;

        echo $user . "累积奖金" . $price . "\n";
        return $money + $price;
    }
}