<?php
/**
 * Created by PhpStorm.
 * User: sundongdong
 * Date: 2018/1/2
 * Time: 17:16
 */
class WorkerLogin extends LoginTemplate {
    public function findLoginUser($loginId)
    {
        // TODO: Implement findLoginUser() method.
        $lm = new LoginModel();
        $lm->setLoginId($loginId);
        $lm->setPassword($this->encryptPwd('workerpwd'));

        return $lm;
    }

    public function encryptPwd($pwd)
    {
        return sha1($pwd); // TODO: Change the autogenerated stub
    }
}