<?php
/**
 * 普通消息
 * Created by PhpStorm.
 * User: sundongdong
 * Date: 2017/12/29
 * Time: 11:56
 */
class CommonMessage extends AbstractMessage {
    public function sendMessage($message, $toUser)
    {
        $message = '(普通)' . $message;
        parent::sendMessage($message, $toUser); // TODO: Change the autogenerated stub
    }
}