<?php
/**
 * Created by PhpStorm.
 * User: sundongdong
 * Date: 2017/12/29
 * Time: 13:53
 */
class SpecialUrgencyMessage extends AbstractMessage {
    public function sendMessage($message, $toUser)
    {
        $message = "(特急)" . $message;
        parent::sendMessage($message, $toUser); // TODO: Change the autogenerated stub
    }

    public function hurry($messageId) {
        // 催促消息
    }
}